version: '2'
services:
  mirakurun:
    image: amaya382/mirakurun:latest
    container_name: mirakurun
    cap_add:
      - SYS_NICE
      - SYS_ADMIN
    devices:
      #- /dev/pt3video0
      #- /dev/pt3video1
      #- /dev/pt3video2
      #- /dev/pt3video3
      #- /dev/bus/usb/00x/00x
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mirakurun/etc/:/usr/local/etc/mirakurun/
      - ./mirakurun/db/:/usr/local/var/db/mirakurun/
    restart: always

  chinachu:
    image: amaya382/chinachu:latest
    container_name: chinachu
    ports:
      - "20772:20772"
    devices:
      #- /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./recorded/:/usr/local/chinachu/recorded/
      - ./chinachu/conf/:/usr/local/chinachu/conf/
      - ./chinachu/data/:/usr/local/chinachu/data/
      - ./chinachu/recorded_command:/usr/local/bin/recorded_command:ro
      - ./chinachu/storage_low_space_command:/usr/local/bin/storage_low_space_command:ro
    environment:
      #- "VAAPI_ENABLED=true" # true or false
      #- "VAAPI_DEVICE=/dev/dri/renderD128" # same as devices
    links:
      - mirakurun
    restart: always
