#!/bin/sh -eux

echo ----- started encoding @`date +%Y/%m/%d/%H:%M:%S` -----
start=`date +%s`
echo $1

raw=$1
out=${1%.*}_.mp4
$CHINACHU_HOME/usr/bin/ffmpeg -i $raw -c:v libx264 -tune animation -c:a copy $out

mkdir -p $DUMP_SITE
mv $raw $DUMP_SITE
mv $out $raw

end=`date +%s`
diff=$(($end - $start))
echo about $(($diff / 60)) min.
echo ----- finished encoding @`date +%Y/%m/%d/%H:%M:%S` -----
echo

exit 0
